services:
  orthanc:
    image: orthancteam/orthanc:latest
    container_name: orthanc-pacs
    ports:
      - "4242:4242"  # DICOM port
      - "8042:8042"  # Web interface & REST API
    environment:
      - ORTHANC_NAME=OrthancTest
      - ORTHANC_AET=ORTHANC
      - ORTHANC_USERNAME=orthanc
      - ORTHANC_PASSWORD=orthanc
      - DICOM_WEB_ENABLED=true
      - VERBOSE_ENABLED=true
      - DICOM_ALWAYS_ALLOW_FIND=true
      - DICOM_ALWAYS_ALLOW_ECHO=true
      - DICOM_ALWAYS_ALLOW_STORE=true
      - DICOM_CHECK_CALLED_AET=false
      - DICOM_CHECK_MODALITY_HOST=false
    volumes:
      - orthanc_data:/var/lib/orthanc/db
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
    restart: unless-stopped
  
  #s3-versitygw:
  #  image: versity/versitygw:v1.0.14
  #  container_name: versitygw
  #  ports:
  #    - "7070:7070"
  #  environment:
  #    - ROOT_ACCESS_KEY=user
  #    - ROOT_SECRET_KEY=password
  #  command: >
  #    posix /tmp/vgw
  s3-rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    environment:
      - RUSTFS_VOLUMES=/data
      - RUSTFS_ADDRESS=0.0.0.0:7070
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:7071
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ACCESS_KEY=user
      - RUSTFS_SECRET_KEY=password
    ports:
      - "7070:7070"
      - "7071:7071"
    volumes:
      - rustfs_data:/data
volumes:
  orthanc_data:
    driver: local
  rustfs_data:
    driver: local